name: CI
on: [push, pull_request]
jobs:
  test-train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      - name: Lint
        run: flake8 .
      - name: Unit tests
        run: pytest -q
      - name: Quick training (v0.1)
        env:
          MODEL_VERSION: v0.1
        run: python training/train_v01.py
      - name: Upload artifacts (v0.1)
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts-v01
          path: artifacts/
